version: '3.8'

networks:
  expense_tracker_network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: expense_tracker_postgres
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - expense_tracker_network


volumes:
  postgres_data:
